In [1]:
import numpy as np
import pandas as pd

print("Практична робота №4")
print("Варіант 5 — Дніпро")
print("Михальчук Юліан, ІТ-42")

df = pd.DataFrame([
    {"замовлення": 1, "місто": "Дніпро",   "ціна": 810,       "кількість": 3},
    {"замовлення": 2, "місто": " Дніпро ", "ціна": "810 грн", "кількість": np.nan},
    {"замовлення": 3, "місто": "ДНІПРО",   "ціна": 820,       "кількість": 3},
    {"замовлення": 4, "місто": "Дніпро",   "ціна": "800 грн", "кількість": 4},
    {"замовлення": 5, "місто": " Дніпро ", "ціна": 830,       "кількість": np.nan},
    {"замовлення": 6, "місто": "ДНІПРО",   "ціна": 810,       "кількість": 2},
    {"замовлення": 7, "місто": "Дніпро",   "ціна": 7290,      "кількість": 3},
    {"замовлення": 7, "місто": "Дніпро",   "ціна": 7290,      "кількість": 3}
])

print(df)

print("\nТипи даних:")
print(df.dtypes)

Практична робота №4
Варіант 5 — Дніпро
Михальчук Юліан, ІТ-42
   замовлення     місто     ціна  кількість
0           1    Дніпро      810        3.0
1           2   Дніпро   810 грн        NaN
2           3    ДНІПРО      820        3.0
3           4    Дніпро  800 грн        4.0
4           5   Дніпро       830        NaN
5           6    ДНІПРО      810        2.0
6           7    Дніпро     7290        3.0
7           7    Дніпро     7290        3.0

Типи даних:
замовлення      int64
місто          object
ціна           object
кількість     float64
dtype: object


In [2]:
# Завдання 2. Пропуски

# 1. Кількість пропусків у кожному стовпці
print("Кількість пропусків:")
print(df.isna().sum())

# 2. Медіана стовпця "кількість"
median_quantity = df["кількість"].median()

print("\nМедіана кількості:", median_quantity)

# Заповнюємо пропуски медіаною
df["кількість"] = df["кількість"].fillna(median_quantity)

print("\nПісля заповнення пропусків:")
print(df)

print("\nПропуски після очищення:")
print(df.isna().sum())

Кількість пропусків:
замовлення    0
місто         0
ціна          0
кількість     2
dtype: int64

Медіана кількості: 3.0

Після заповнення пропусків:
   замовлення     місто     ціна  кількість
0           1    Дніпро      810        3.0
1           2   Дніпро   810 грн        3.0
2           3    ДНІПРО      820        3.0
3           4    Дніпро  800 грн        4.0
4           5   Дніпро       830        3.0
5           6    ДНІПРО      810        2.0
6           7    Дніпро     7290        3.0
7           7    Дніпро     7290        3.0

Пропуски після очищення:
замовлення    0
місто         0
ціна          0
кількість     0
dtype: int64


### Пояснення
Пропуски у стовпці «кількість» заповнено медіаною. Медіана доречніша за середнє для невеликої вибірки з 8 спостережень, оскільки вона менш чутлива до нетипових значень і не так сильно зміщується через окремі крайні значення.

In [3]:
# Завдання 3. Дублікати

# 1. Повні дублікати — без subset
print("Кількість повних дублікатів:")
print(df.duplicated().sum())

print("\nПовні дублікати:")
print(df[df.duplicated()])

# 2. Перевірка з subset
# У нашому наборі замовлення ідентифікуємо за номером замовлення
print("\nДублікати за номером замовлення:")
print(df.duplicated(subset=["замовлення"]).sum())

print("\nРядки-дублікати за номером замовлення:")
print(df[df.duplicated(subset=["замовлення"])])

# 3. Видаляємо дублікат
df = df.drop_duplicates(subset=["замовлення"]).copy()

print("\nПісля видалення дубліката:")
print(df)

print("\nКількість рядків залишилась:", len(df))

Кількість повних дублікатів:
1

Повні дублікати:
   замовлення   місто  ціна  кількість
7           7  Дніпро  7290        3.0

Дублікати за номером замовлення:
1

Рядки-дублікати за номером замовлення:
   замовлення   місто  ціна  кількість
7           7  Дніпро  7290        3.0

Після видалення дубліката:
   замовлення     місто     ціна  кількість
0           1    Дніпро      810        3.0
1           2   Дніпро   810 грн        3.0
2           3    ДНІПРО      820        3.0
3           4    Дніпро  800 грн        4.0
4           5   Дніпро       830        3.0
5           6    ДНІПРО      810        2.0
6           7    Дніпро     7290        3.0

Кількість рядків залишилась: 7


In [4]:
# Завдання 4. Типи даних і узгодження категорій

# 1. Приводимо ціну до числового типу float
df["ціна"] = (
    df["ціна"]
    .astype(str)
    .str.replace(" грн", "", regex=False)
    .astype(float)
)

print("Тип стовпця 'ціна':", df["ціна"].dtype)
print(df["ціна"])

# 2. Узгоджуємо назви міста
df["місто"] = df["місто"].str.strip().str.lower()

# Канонічний запис
df["місто"] = df["місто"].replace({
    "дніпро": "Дніпро"
})

print("\nУнікальні назви міста:")
print(df["місто"].unique())

print("\nОчищений DataFrame:")
print(df)

Тип стовпця 'ціна': float64
0     810.0
1     810.0
2     820.0
3     800.0
4     830.0
5     810.0
6    7290.0
Name: ціна, dtype: float64

Унікальні назви міста:
['Дніпро']

Очищений DataFrame:
   замовлення   місто    ціна  кількість
0           1  Дніпро   810.0        3.0
1           2  Дніпро   810.0        3.0
2           3  Дніпро   820.0        3.0
3           4  Дніпро   800.0        4.0
4           5  Дніпро   830.0        3.0
5           6  Дніпро   810.0        2.0
6           7  Дніпро  7290.0        3.0


In [5]:
# Завдання 5. Пошук викидів методом IQR

Q1 = df["ціна"].quantile(0.25)
Q3 = df["ціна"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Нижня межа:", lower_bound)
print("Верхня межа:", upper_bound)

# Знаходимо викиди
outliers = df[
    (df["ціна"] < lower_bound) |
    (df["ціна"] > upper_bound)
]

print("\nЗнайдені викиди:")
print(outliers)

# Видаляємо викиди
df_clean = df[
    (df["ціна"] >= lower_bound) &
    (df["ціна"] <= upper_bound)
].copy()

print("\nОчищений набір:")
print(df_clean)

print("\nКількість рядків після очищення:", len(df_clean))

Q1: 810.0
Q3: 825.0
IQR: 15.0
Нижня межа: 787.5
Верхня межа: 847.5

Знайдені викиди:
   замовлення   місто    ціна  кількість
6           7  Дніпро  7290.0        3.0

Очищений набір:
   замовлення   місто   ціна  кількість
0           1  Дніпро  810.0        3.0
1           2  Дніпро  810.0        3.0
2           3  Дніпро  820.0        3.0
3           4  Дніпро  800.0        4.0
4           5  Дніпро  830.0        3.0
5           6  Дніпро  810.0        2.0

Кількість рядків після очищення: 6


## Завдання 5. Рішення щодо викиду

Значення 7290 грн було визначено методом IQR як викид. У цьому наборі я вважаю його помилкою вводу, оскільки базова ціна товару становить 810 грн, а 7290 грн у 9 разів перевищує її. Оскільки всі записи стосуються одного товару, таке різке відхилення виглядає як помилкове значення. Тому його доцільно вилучити з очищеного набору.

## Відповіді на питання

**1. Чому заповнення пропуску середнім, а не медіаною, може згодом спотворити стандартне відхилення?**  
Середнє значення чутливе до крайніх значень і викидів. У невеликій вибірці вони можуть помітно змістити середнє, тому заповнення ним пропусків може вплинути на розподіл даних і стандартне відхилення. Медіана стійкіша до таких значень.

**2. У чому різниця між `duplicated()` без `subset` і з `subset`?**  
Без `subset` рядок вважається дублікатом лише тоді, коли збігаються значення в усіх стовпцях. З `subset` перевіряються тільки вибрані стовпці, тому два рядки можуть вважатися дублікатами навіть тоді, коли інші їхні значення відрізняються.

**3. Чому автоматичне видалення всіх значень поза межами IQR не завжди правильне?**  
Значення поза межами IQR не обов'язково є помилками. Це можуть бути реальні рідкісні або екстремальні спостереження. Тому перед видаленням потрібно враховувати зміст даних і причину появи такого значення.